#!/bin/bash

python preprocess.py -train_src IntrinsicTasks/simple_relabeling_input_train_f.txt -train_tgt IntrinsicTasks/simple_relabeling_output_train_f.txt -valid_src IntrinsicTasks/simple_relabeling_input_valid_f.txt -valid_tgt IntrinsicTasks/simple_relabeling_output_valid_f.txt  -save_data IntrinsicTasks/Task1_Seq/Task1_Seq
python preprocess.py -train_src IntrinsicTasks/simple_relabeling_input_train_w_gorn.txt -train_tgt IntrinsicTasks/simple_relabeling_output_train_w_gorn.txt -valid_src IntrinsicTasks/simple_relabeling_input_valid_w_gorn.txt -valid_tgt IntrinsicTasks/simple_relabeling_output_valid_w_gorn.txt  -save_data IntrinsicTasks/Task1_Our/Task1_Our
python embeddings_to_torch.py -emb_file_both glove.6B.200d.txt -output_file IntrinsicTasks/Task1_Seq/embeddings -dict_file IntrinsicTasks/Task1_Seq/Task1_Seq.vocab.pt
python train.py -save_model IntrinsicTasks/Task1_Seq/model -batch_size 20 -layers 2 -word_vec_size 200 -pre_word_vecs_enc "IntrinsicTasks/Task1_Seq/embeddings.enc.pt" -pre_word_vecs_dec "IntrinsicTasks/Task1_Seq/embeddings.dec.pt" -data IntrinsicTasks/Task1_Seq/Task1_Seq --gpu_ranks 0 --learning_rate 0.1 --valid_steps 100 &> IntrinsicTasks/Task1_Seq/logs &
python train.py -save_model IntrinsicTasks/Task1_Trans/model -batch_size 1000 -layers 2 -word_vec_size 200 -pre_word_vecs_enc IntrinsicTasks/Task1_Seq/embeddings.enc.pt -pre_word_vecs_dec IntrinsicTasks/Task1_Seq/embeddings.dec.pt -data IntrinsicTasks/Task1_Seq/Task1_Seq --gpu_ranks 0 --learning_rate 0.1 -rnn_size 200 --valid_steps 100 -encoder_type transformer -decoder_type transformer --position_encoding
python train.py -save_model IntrinsicTasks/Task1_Our/model -batch_size 1000 -layers 2 -word_vec_size 200 -pre_word_vecs_enc IntrinsicTasks/Task1_Our/embeddings.enc.pt -pre_word_vecs_dec IntrinsicTasks/Task1_Our/embeddings.dec.pt -data IntrinsicTasks/Task1_Our/Task1_Our --gpu_ranks 0 --learning_rate 0.1 -rnn_size 200 --valid_steps 100 -encoder_type transformer -decoder_type transformer --position_encoding --src_gorn_position_encoding --tgt_gorn_position_encoding &> IntrinsicTasks/Task1_Our/logs &


python preprocess.py -train_src data_gen/input/train_value.txt -train_tgt data_gen/depth0/train_value.txt -valid_src data_gen/input/valid_value.txt -valid_tgt data_gen/depth0/valid_value.txt  -save_data data_gen/depth0_logs/depth0
python preprocess.py -train_src data_gen/input/train_gorn.txt -train_tgt data_gen/depth0/train_gorn.txt -valid_src data_gen/input/valid_gorn.txt -valid_tgt data_gen/depth0/valid_gorn.txt  -save_data data_gen/depth0_gorn/depth0
python embeddings_to_torch.py -emb_file_both glove.6B.200d.txt -output_file data_gen/depth0_gorn/embeddings -dict_file data_gen/depth0_gorn/depth0.vocab.pt
python train.py -save_model data_gen/depth0_gorn/model -batch_size 1000 -layers 2 -word_vec_size 200 -pre_word_vecs_enc data_gen/depth0_gorn/embeddings.enc.pt -pre_word_vecs_dec data_gen/depth0_gorn/embeddings.dec.pt -data data_gen/depth0_gorn/depth0 --gpu_ranks 0 --learning_rate 0.1 -rnn_size 200 --valid_steps 100 -encoder_type transformer -decoder_type transformer --position_encoding --src_gorn_position_encoding --tgt_gorn_position_encoding --train_steps 50000 &> data_gen/depth0_gorn/logs &

python embeddings_to_torch.py -emb_file_both glove.6B.200d.txt -output_file data_gen/depth0_logs/embeddings -dict_file data_gen/depth0_logs/depth0.vocab.pt
python train.py -save_model data_gen/depth0_logs/model -batch_size 1000 -layers 2 -word_vec_size 200 -pre_word_vecs_enc data_gen/depth0_logs/embeddings.enc.pt -pre_word_vecs_dec data_gen/depth0_logs/embeddings.dec.pt -data data_gen/depth0_logs/depth0 --gpu_ranks 0 --learning_rate 0.1 -rnn_size 200 --valid_steps 100 -encoder_type transformer -decoder_type transformer --position_encoding --train_steps 50000 &> data_gen/depth0_logs/logs &


python preprocess.py -train_src data_gen/input/train_value.txt -train_tgt data_gen/parent12/train_value.txt -valid_src data_gen/input/valid_value.txt -valid_tgt data_gen/parent12/valid_value.txt  -save_data data_gen/parent12_logs/depth0
python embeddings_to_torch.py -emb_file_both glove.6B.200d.txt -output_file data_gen/parent12_logs/embeddings -dict_file data_gen/parent12_logs/depth0.vocab.pt
python train.py -save_model data_gen/parent12_logs/model -batch_size 1000 -layers 2 -word_vec_size 200 -pre_word_vecs_enc data_gen/parent12_logs/embeddings.enc.pt -pre_word_vecs_dec data_gen/parent12_logs/embeddings.dec.pt -data data_gen/parent12_logs/depth0 --gpu_ranks 0 --learning_rate 0.1 -rnn_size 200 --valid_steps 100 -encoder_type transformer -decoder_type transformer --position_encoding --train_steps 100000 &> data_gen/parent12_logs/logs &

python preprocess.py -train_src data_gen/input_10/train_value.txt -train_tgt data_gen/sibling1_10/train_value.txt -valid_src data_gen/input_10/valid_value.txt -valid_tgt data_gen/sibling1_10/valid_value.txt  -save_data data_gen/sibling1_10_logs/depth0
python embeddings_to_torch.py -emb_file_both glove.6B.200d.txt -output_file data_gen/sibling1_10_logs/embeddings -dict_file data_gen/sibling1_10_logs/depth0.vocab.pt
python train.py -save_model data_gen/sibling1_10_logs/model -batch_size 1000 -layers 2 -word_vec_size 200 -pre_word_vecs_enc data_gen/sibling1_10_logs/embeddings.enc.pt -pre_word_vecs_dec data_gen/sibling1_10_logs/embeddings.dec.pt -data data_gen/sibling1_10_logs/depth0 --gpu_ranks 0 --learning_rate 0.1 -rnn_size 200 --valid_steps 100 -encoder_type transformer -decoder_type transformer --position_encoding --train_steps 100000 &> data_gen/sibling1_10_logs/logs &

python preprocess.py -src_seq_length 200 -tgt_seq_length 200 -train_src data_tree/input/train_tree.txt -train_tgt data_tree/input/train_tree.txt -valid_src data_tree/input/valid_tree.txt -valid_tgt data_tree/input/valid_tree.txt  -save_data data_tree/tree_logs/depth0
python embeddings_to_torch.py -emb_file_both glove.6B.200d.txt -output_file data_tree/tree_logs/embeddings -dict_file data_tree/tree_logs/depth0.vocab.pt
python train.py -save_model data_tree/tree_logs/model -batch_size 256 -layers 2 -word_vec_size 200 -pre_word_vecs_enc data_tree/tree_logs/embeddings.enc.pt -pre_word_vecs_dec data_tree/tree_logs/embeddings.dec.pt -data data_tree/tree_logs/depth0 --gpu_ranks 0 --learning_rate 0.1 -rnn_size 200 --valid_steps 100 -encoder_type transformer -decoder_type transformer --position_encoding --train_steps 100000 &> data_tree/tree_logs/logs &
python train.py -save_model data_tree/tree_logs/model -batch_size 256 -layers 2 -word_vec_size 200 -pre_word_vecs_enc data_tree/tree_logs/embeddings.enc.pt -pre_word_vecs_dec data_tree/tree_logs/embeddings.dec.pt -data data_tree/tree_logs/depth0 --gpu_ranks 0 --learning_rate 0.1 -rnn_size 200 --valid_steps 100 --train_steps 100000 &> data_tree/tree_logs/logs &

onmt_preprocess -train_src input/train_tree.txt -train_tgt input/train_tree.txt -valid_src input/valid_tree.txt -valid_tgt input/valid_tree.txt -save_data data/demo -overwrite -src_seq_length 200 -tgt_seq_length 200
onmt_train -data data/demo -save_model demo-model -batch_size 512 -layers 2 --gpu_ranks 0 --learning_rate 0.1 -rnn_size 200 --valid_steps 100 --train_steps 50000 &> tree_logs/logs &
onmt_train -data data/demo -save_model demo-model -batch_size 512 -layers 2 --gpu_ranks 0 --learning_rate 0.1 --valid_steps 100 -word_vec_size 200 -rnn_size 200 -encoder_type transformer -decoder_type transformer --position_encoding --train_steps 100000 &> tree_logs/logs &

onmt_preprocess -train_src data/input/train.txt -train_tgt data/depth0/train.txt -valid_src data/input/valid.txt -valid_tgt data/depth0/valid.txt -save_data data/depth0/depth0 -overwrite -src_seq_length 200 -tgt_seq_length 200
onmt_train -data data/depth0/depth0 -save_model logs/depth0/depth0-model -batch_size 1024 -layers 2 --gpu_ranks 0 --learning_rate 0.1 --valid_steps 100 -word_vec_size 200 -rnn_size 200 -encoder_type transformer -decoder_type transformer --position_encoding --train_steps 100000 &> logs/depth0/logs &

onmt_preprocess -train_src tree_data/input/train.txt -train_tgt tree_data/parent1/train.txt -valid_src tree_data/input/valid.txt -valid_tgt tree_data/parent1/valid.txt -save_data data/parent1/parent1 -overwrite -src_seq_length 200 -tgt_seq_length 200
onmt_train -data data/parent1/parent1 -save_model logs/parent1/parent1-model -batch_size 1024 -layers 2 --gpu_ranks 0 --learning_rate 0.1 --valid_steps 100 -word_vec_size 200 -rnn_size 200 -encoder_type transformer -decoder_type transformer --position_encoding --train_steps 100000 &> logs/parent1/logs &

python preprocess.py -train_src tree_position/input/train.txt -train_tgt tree_position/parent1/train.txt -valid_src tree_position/input/valid.txt -valid_tgt tree_position/parent1/valid.txt -save_data tree_data/parent1/parent1  -src_seq_length 200 -tgt_seq_length 200
python train.py -data tree_data/parent1/parent1 -save_model tree_logs/parent1/parent1-model -batch_size 1024 -layers 2 --gpu_ranks 0 --learning_rate 0.1 --valid_steps 100 -word_vec_size 200 -rnn_size 200 -encoder_type transformer -decoder_type transformer --position_encoding --train_steps 100000 &> tree_logs/parent1/logs &

python preprocess.py -train_src tree_position/input/train.txt -train_tgt tree_position/parent1/train.txt -valid_src tree_position/input/valid.txt -valid_tgt tree_position/parent1/valid.txt -save_data tree_data/parent1/parent1  -src_seq_length 200 -tgt_seq_length 200
python train.py -data tree_data/parent1/parent1 -save_model tree_logs/parent1/parent1-model -batch_size 1024 -layers 2 --gpu_ranks 0 --learning_rate 0.1 --valid_steps 100 -word_vec_size 200 -rnn_size 200 -encoder_type transformer -decoder_type transformer --position_encoding --train_steps 100000 &> tree_logs/parent1/logs &
